require('dotenv').config()
//const Scalping_Ssl_Cci_Atr = require('./estrategias/Futuros/Scalping_Ssl_Cci_Atr')
//const Scalping_Ssl_Cci_Atr2 = require('./estrategias/Futuros/Scalping_Ssl_Cci_Atr2')
//const DobleMediasAtr = require('./estrategias/Futuros/DobleMediasAtr')
const MTF_Layered_rsi = require('./estrategias/Futuros/MTF_Layered_rsi')
//Scalping_Ssl_Cci_Atr.init()
//Scalping_Ssl_Cci_Atr2.init()
//DobleMediasAtr.init()
MTF_Layered_rsi.init()